### ISSUE TITLE
set_default only works with items in the first step of a workflow

### ISSUE THREAD

**Issue by danlamanna** [Kitware/romanesco#167]
```
add_two = {
    "inputs": [{"name": "a", "type": "number", "format": "number"}],
    "outputs": [{"name": "b", "type": "number", "format": "number"}],
    "mode": "python",
    "script": "b = a + 2"}

multiply = {
    "inputs": [{"name": "in1", "type": "number", "format": "number"},
               {"name": "in2", "type": "number", "format": "number"}],
    "outputs": [{"name": "out", "type": "number", "format": "number"}],
    "mode": "python",
            "script": "out = in1 * in2"}

wf.add_task(add_two, "a2")
wf.add_task(multiply, "m")

wf.connect_tasks("a2", "m", {"b": "in2"})

wf.set_default("m.in1", {"format": "number", "data": 1})

romanesco.run(wf, inputs={"a": {"format": "number", "data": 10}})
```

This will throw the following traceback:
```
Traceback (most recent call last):
  File "workflow.py", line 27, in <module>
    "data": 10}})
  File "/home/dan/projects/romanesco/romanesco/utils.py", line 285, in wrapped
    return fn(*args, **kwargs)
  File "/home/dan/projects/romanesco/romanesco/__init__.py", line 228, in run
    raise Exception("Required input '%s' not provided." % name)
Exception: Required input 'in1' not provided.
```

Setting the default on the actual task itself works.

**Comment by danlamanna** [comment]
In addition, for some reason on the last line if I refer to "a" as "a2.a" it will throw an exception saying "a" was not provided.

**Comment by jeffbaumes** [comment]
I believe what is going on here is that the name of the workflow inputs are not prefixed by the task id unless the input names match in multiple subtasks. So the inputs should be referred to as `in1` and `a`, not `m.in1` and `a2.a`. It would break the spec to have workflow inputs to have multiple names.

So perhaps this is a documentation problem but it is not unexpected behavior.
